# Site settings
title: "</Marita>"
email: "marita.martha23@gmail.com"
description: >-
  "Software Developer | Technical Support | Portfolio showcasing resume, projects, lab challenges, and community impact."
github_username: Martha-Iradukunda
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes   # required for theme, but won’t show anywhere
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Africa/Nairobi

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# Author profile
author:
  name   : "Martha I. Rekeraho"
  avatar : "/assets/images/bio-photo.jpg"   # replace with your photo in assets/images
    bio  : >-
    "Applied Computer Technology graduate|Full-Stack Developer|IT Support|Cisco Ethical Hacker|Passionate about tech solutions & community impact"

  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://tinyurl.com/3njn2wzb"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://tinyurl.com/mvzx3bvu"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:marita.martha23@gmail.com"
    - label: "Phone"
      icon: "fas fa-fw fa-phone"
      url: "tel:+254790367122"

# Footer
footer:
  content: "© 2025 Martha I. Rekeraho. Powered by Marita."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://tinyurl.com/3njn2wzb"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://tinyurl.com/mvzx3bvu"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:marita.martha23@gmail.com"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Navigation (main menu)
navigation:
  - title: "Home"
    url: /
  - title: "Resume Outline"
    url: /resume/
  - title: "Projects"
    url: /projects/
  - title: "Lab Challenges"
    url: /lab-challenges/
  - title: "Contacts"
    url: /contacts/
